name = "SnR Private Tests"
author = "Slimeist"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "218ab92b87baf830b090f8e5a466d26dabac96bdbb6ee97f1db5954ed3aee41e"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
