name = "SnR Private Tests"
author = "Slimeist"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "737be954e460eaa7d027bb3969b1295af73dc5d78cc442a86214f141df814569"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
